// <auto-generated />
using System;
using LookUp.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LookUp.Domain.Migrations
{
    [DbContext(typeof(LookUpDbContext))]
    [Migration("20240304062848_addModifiedOnAndBy")]
    partial class addModifiedOnAndBy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LookUp.Domain.Entities.AttributesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Attributes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("661d80dc-106f-45a2-b94b-350effe7ff4e"),
                            ModifiedOn = new DateTime(2024, 3, 4, 13, 28, 48, 466, DateTimeKind.Local).AddTicks(5249),
                            Status = 0,
                            Type = 0,
                            Unit = "Tes1"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
