version: '3.4'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server
    container_name: mssql-bekal
    environment:
      - MSSQL_SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
  
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    hostname: zookeeper
    container_name: zookeeper-bekal
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.3.0
    container_name: broker-bekal
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  kafka-init:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka-init-bekal
    depends_on:
      - zookeeper
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      # blocks until kafka is reachable
      kafka-topics --bootstrap-server broker:29092 --list

      echo -e 'Creating kafka topics'
      kafka-topics --bootstrap-server broker:29092 --create --if-not-exists --topic Users --replication-factor 1 --partitions 1
      kafka-topics --bootstrap-server broker:29092 --create --if-not-exists --topic Lookups --replication-factor 1 --partitions 1
      kafka-topics --bootstrap-server broker:29092 --create --if-not-exists --topic Stores --replication-factor 1 --partitions 1
      kafka-topics --bootstrap-server broker:29092 --create --if-not-exists --topic Carts --replication-factor 1 --partitions 1
      kafka-topics --bootstrap-server broker:29092 --create --if-not-exists --topic Payments --replication-factor 1 --partitions 1

      echo -e 'Successfully created the following topics:'
      kafka-topics --bootstrap-server broker:29092 --list
      "
 
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui-bekal
    depends_on:
      - broker
    ports:
      - "8080:8080"
    restart: "no"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=broker:29092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181



  user.graphql:
    image: ${DOCKER_REGISTRY-}usergraphql
    container_name: user-bekal
    build:
      context: .
      dockerfile: User GraphQL/Dockerfile
    environment: 
      - ConnectionStrings__User_Db_Conn=Server=mssql; Database=UserDatabase; User=SA; Password=Pass@word; TrustServerCertificate=True
      - JWT__ExpireDays=60
      - JWT__Secret=JWTAuthorization2024Bekal.NetMicroservices
      - JWT__ValidAudience=*
      - JWT__ValidIssuer=*
      - KafkaProducer__PriducerConfig__BootstrapServers=broker:29092
      - KafkaProducer__Topic=Users
#tidak boleh ada spasi setelah samadengan =
    ports:
      - "51080:80"
    depends_on:
      - mssql
      - broker

  lookup.graphql:
    image: ${DOCKER_REGISTRY-}lookupgraphql
    container_name: lookup-bekal
    build:
      context: .
      dockerfile: LookUp.GraphQL/Dockerfile
    environment:
      - ConnectionStrings__User_Db_Conn=Server=mssql; Database=LookUpDatabase; User=SA; Password=Pass@word; TrustServerCertificate=True
      - JWT__ExpireDays=60
      - JWT__Secret=JWTAuthorization2024Bekal.NetMicroservices
      - JWT__ValidAudience=*
      - JWT__ValidIssuer=*
      - KafkaProducer__PriducerConfig__BootstrapServers=broker:29092
      - KafkaProducer__Topic=Lookups
    ports:
      - "52080:80"
    depends_on:
      - mssql
      - broker

  store.graphql:
    image: ${DOCKER_REGISTRY-}storegraphql
    container_name: store-bekal
    build:
      context: .
      dockerfile: Store.GraphQL/Dockerfile
    environment:
      - ConnectionStrings__User_Db_Conn=Server=mssql; Database=StoreDatabase; User=SA; Password=Pass@word; TrustServerCertificate=True
      - JWT__ExpireDays=60
      - JWT__Secret=JWTAuthorization2024Bekal.NetMicroservices
      - JWT__ValidAudience=*
      - JWT__ValidIssuer=*
      - KafkaConsumer__ConsumerConfig__AutoOffsetReset=Earliest
      - KafkaConsumer__ConsumerConfig__BootstrapServers=broker:29092
      - KafkaConsumer__ConsumerConfig__EnableAutoCommit=False
      - KafkaConsumer__ConsumerConfig__GroupId=Stores      
      - KafkaProducer__PriducerConfig__BootstrapServers=broker:29092      
      - KafkaConsumer__Topics__0=Lookups     
      - KafkaProducer__Topic=Stores
    ports:
      - "53080:80"
    depends_on:
      - mssql
      - broker


  order.graphql:
    image: ${DOCKER_REGISTRY-}ordergraphql
    container_name: order-bekal
    build:
      context: .
      dockerfile: Order.GraphQL/Dockerfile
    environment:
      - ConnectionStrings__User_Db_Conn=Server=mssql; Database=OrderDatabase; User=SA; Password=Pass@word; TrustServerCertificate=True
      - JWT__ExpireDays=60
      - JWT__Secret=JWTAuthorization2024Bekal.NetMicroservices
      - JWT__ValidAudience=*
      - JWT__ValidIssuer=*
      - KafkaConsumer__ConsumerConfig__AutoOffsetReset=Earliest
      - KafkaConsumer__ConsumerConfig__BootstrapServers=broker:29092
      - KafkaConsumer__ConsumerConfig__EnableAutoCommit=False
      - KafkaConsumer__ConsumerConfig__GroupId=Carts
      - KafkaConsumer__Topics__0=Users
      - KafkaConsumer__Topics__1=Stores
      - KafkaProducer__PriducerConfig__BootstrapServers=broker:29092
      - KafkaProducer__Topic=Carts
    ports:
      - "55080:80"
    depends_on:
      - mssql
      - broker

    


  gateway.graphql:
    image: ${DOCKER_REGISTRY-}gatewaygraphql
    container_name: gateway-bekal
    build:
      context: .
      dockerfile: Gateway.GraphQL/Dockerfile
    environment:
      - HttpClients__UserService=http://user.graphql/graphql
      - HttpClients__LookupService=http://lookup.graphql/graphql
      - HttpClients__OrderService=http://order.graphql/graphql
      - HttpClients__StoreService=http://store.graphql/graphql
      - HttpClients__PaymentService=http://payment.graphql/graphql
    ports:
      - "54080:80"
 

  payment.graphql:
    image: ${DOCKER_REGISTRY-}paymentgraphql
    container_name: payment-bekal
    build:
      context: .
      dockerfile: Payment.GraphQL/Dockerfile
    environment:
      - ConnectionStrings__Payment_Db_Conn=Server=mssql; Database=PaymentDatabase; User=sa; Password=Pass@word;TrustServerCertificate=True
      - KafkaConsumer__ConsumerConfig__AutoOffsetReset=Earliest
      - KafkaConsumer__ConsumerConfig__BootstrapServers=broker:29092
      - KafkaConsumer__ConsumerConfig__EnableAutoCommit=False
      - KafkaConsumer__ConsumerConfig__GroupId=Payments
      - KafkaConsumer__Topics__0=Users
      - KafkaConsumer__Topics__1=Stores
      - KafkaConsumer__Topics__2=Carts
      - KafkaProducer__PriducerConfig__BootstrapServers=broker:29092
      - KafkaProducer__Topic=Payments
    ports:
      - "56080:80"
    depends_on:
      - mssql
      - broker

